// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxTIO_xpScpGS-2_XZ6_V59fRoNkBhO_w',
    appId: '1:815880256694:web:d0625997c20130f4f9fa17',
    messagingSenderId: '815880256694',
    projectId: 'flutter-e-mart',
    authDomain: 'flutter-e-mart.firebaseapp.com',
    storageBucket: 'flutter-e-mart.appspot.com',
    measurementId: 'G-QERLJ5HKLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgb4ir3-Mb7T1JdlirB3Fb71QAk0FTuyU',
    appId: '1:815880256694:android:ef9dcebf75a4c9a2f9fa17',
    messagingSenderId: '815880256694',
    projectId: 'flutter-e-mart',
    storageBucket: 'flutter-e-mart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnk1zSgmMubJmD5BrHCTSbUIPscLOwyMo',
    appId: '1:815880256694:ios:d974220683f94300f9fa17',
    messagingSenderId: '815880256694',
    projectId: 'flutter-e-mart',
    storageBucket: 'flutter-e-mart.appspot.com',
    iosClientId: '815880256694-eimjuq3vdtitqbu8l72u9uco6l7op87u.apps.googleusercontent.com',
    iosBundleId: 'com.alaminkarno.flutterEMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnk1zSgmMubJmD5BrHCTSbUIPscLOwyMo',
    appId: '1:815880256694:ios:d974220683f94300f9fa17',
    messagingSenderId: '815880256694',
    projectId: 'flutter-e-mart',
    storageBucket: 'flutter-e-mart.appspot.com',
    iosClientId: '815880256694-eimjuq3vdtitqbu8l72u9uco6l7op87u.apps.googleusercontent.com',
    iosBundleId: 'com.alaminkarno.flutterEMart',
  );
}
